const  options = [
  { value: "resturants", label: "Resturants" },
  { value: "holiday", label: "Holiday" },
  { value: "health", label: "Health Center" },
  { value: "gadgets", label: "Gadgets" },
  { value: "fashion", label: "Fashion" },
  { value: "grooming", label: "Grooming" },
  { value: "gifts", label: "Gifts" },
  { value: "motors", label: "Motors" },
  { value: "jewelery", label: "Jewelery" },
  { value: "properties", label: "Properties" },
  { value: "education", label: "Education" },
  { value: "sports", label: "Sports" },
  { value: "beauty", label: "Beauty" },
  { value: "electronics", label: "Electronics" },
  { value: "food", label: "Food" },
  { value: "travel", label: "Travel" },
  { value: "furniture", label: "Furniture" },
  { value: "books", label: "Books" },
  { value: "pets", label: "Pets" },
  { value: "services", label: "Services" },
  { value: "others", label: "Others" },
];

export { options}